apiVersion: apps/v1
kind: Deployment
metadata:
  name: bms-app
spec:
  replicas: 1  # IMPORTANT: Use 1, not 2
  selector:
    matchLabels:
      app: bms
  template:
    metadata:
      labels:
        app: bms
    spec:
      tolerations:
      - operator: "Exists"

      containers:
      - name: bms-container
        image: sharmanayan/bms:latest
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        ports:
        - containerPort: 3000